# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               gdcs92
tagline:             computational science & applied maths

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Vitae: '/vitae/'
  Projects: '/projects/'
